name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1

      # This is added as a tempory fix, due to a Bug in MSBuild/Visual Studio
      # For more info see: https://developercommunity2.visualstudio.com/t/IntelliSense-fails-because-designtime-bu/1157856
      - name: Temp fix for VS Bug
        run: cp sealighter\Directory.Build.props krabsetw\Microsoft.O365.Security.Native.ETW\

      - name: Build Debug
        run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Debug sealighter.sln

      - name: Build Release
        run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Release sealighter.sln
